const CHANNEL_GENERATE_KEYS = 'generate_keys'
const CHANNEL_GENERATE_PUBLIC_KEYS = 'generate_public_key'
const CHANNEL_COPY_KEY = 'copy_key'
const CHANNEL_SAVE_KEY = 'save_key'
const GET_ALL_CHANNELS = [CHANNEL_GENERATE_KEYS, CHANNEL_GENERATE_PUBLIC_KEYS, CHANNEL_COPY_KEY, CHANNEL_SAVE_KEY]

module.exports = {
  CHANNEL_GENERATE_KEYS,
  CHANNEL_GENERATE_PUBLIC_KEYS,
  CHANNEL_COPY_KEY,
  CHANNEL_SAVE_KEY,
  GET_ALL_CHANNELS
}
